# Config File for Backup Management Script "bck_mgmt"

backup_repository:

  - directory: /data/backups/test_repo1 # defines the base directory of your backup repository
    alias: Test-Repo 1          # optional: defines an alias for this repo which will be used in logs and reports etc.
    pattern: "Test*.bck"        # defines the pattern of the backup files you want to process. Use "*" as wildcard and put the entire expression into quotation marks.
    keep: 3                     # defines how many backup files you want to keep in the base directory
    warn_age: 7                 # optional: the script will output a warning, if the newest file in the repo is older than the defined value in days
    warn_bytes: 1000            # optional: the script will output a warning, if the newest file in the repo is smaller than the defined value in bytes.
    delete_old: true            # if you set this to false, the script will not actually delete files but log the files, which would have been deleted. Usefull for tests. 
    move_old_to: /data/backups/test_repo1/archive/ # optional: move files to this directory instead of deleting them.
    weekly:                     # optional: defines a directory to keep weekly backups. Directory must already exist.
        directory: /data/backups/test_repo1/weekly/
        keep: 1                 # how many weekly backups you want to keep
    monthly:                    # optional: defines a directory to keep monthly backups. Directory must already exist.
        directory: /data/backups/test_repo1/monthly/
        keep: 12                # how many monthly backups you want to keep
    yearly:                     # optional: defines a directory to keep yearly backups. Directory must already exist.
        directory: /data/backups/test_repo1/yearly/
        keep: 10                # how many yearly backups you want to keep

  - directory: /data/backups/test_repo2
    alias: Test-Repo 2
    pattern: "**/Test2*.bck"    # "**" means "this directory and all subdirectories, recursively". Use with caution!
    keep: 10
    delete_old: true

  - directory: /data/backups/config_archive1
    pattern: "*.cfg"
    keep: 10
    warn_age: 10
    warn_bytes: 10
    delete_old: true
    compliance_check: 
      - regex: '^ip access-list 1 1\.2\.3\.4$' # Put 'single quotes' around all regexes and violation messages!
        violation_message: 'IP 1.2.3.4 is missing in ACL 1!' # optional, but usefull especially with long regexes.
      - regex: '^password (default|unsafe)'
        must_not_match: true    # regex must not match -> raise a violation if it matches
        violation_message: 'Unsafe Password "\1" set!' # \1 will be replaced by the 1st group match. \2 would be replaced by the 2nd and so on.
      - regex: '^ip access-list 1 (?!1\.2\.3\.4$|2\.3\.4\.5$)(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'
        must_not_match: true
        violation_message: 'Unallowed IP \1 in ACL 1!'
    compare_with_previous: true # compare newest file with previous file and warn if there are differences. Note: only works for text files!
    
#    ...                        # you can add as many repositorys as you want here

logging:
    level: info                 # possible values: debug | info | warning | error
    file: /var/log/bck_mgmt.log # log file destination. If omitted, log will go to stdout.

